# ============================
# Modulus TOML Schema v0.1
# ============================

# ----------------------------
# [openai.<name>]
# Defines a model provider
# ----------------------------
[provider.openai]
type = "openai"
api_key = "@env:OPENAI_API_KEY"

[provider.anthropic]
type = "anthropic"
api_key = "@env:ANTHROPIC_API_KEY"

# ----------------------------
# [llm.<name>]
# Defines a language model
# ----------------------------
[llm.claude-opus-4-1]
provider = "anthropic"
model = "claude-opus-4-1"
temperature = 0.2
max_tokens = 256

[llm.gpt-5]
provider = "openai"
model = "gpt-5-chat-latest"
max_tokens = 512

# ----------------------------
# [embedding.<name>]
# Defines an embedding model
# ----------------------------
[embedding.ada]
provider = "openai"
model = "text-embedding-ada-002"

# ----------------------------
# [memory.<name>]
# Defines vector memory store
# ----------------------------
[memory.vectorstore]
type = "chroma"
persist = true
namespace = "main"
embedding_model = "text-embedding-ada-002"

# ----------------------------
# [[tool]]
# External API, function, or memory lookup
# ----------------------------
[tool.foo]
type = "function"
function = "functions/foo.foofn"

# ----------------------------
# [[agent]]
# Defines an AI persona
# ----------------------------
[agent.creator]
prompt = "@file:prompts/creator.prompt"
tools = ["foo"]
memory = "vectorstore"
llm = "claude-opus-4-1"

[agent.analyzer]
prompt = "@file:prompts/analyzer.prompt"
tools = ["foo"]
memory = "vectorstore"
llm = "gpt-5"

# ----------------------------
# [task.<name>]
# Pipeline or multi-agent orchestration
# ----------------------------
[task.analysis]
description = "Can one LLM deceive another?"
flow = ["creator", "analyzer"]
input_schema = { question = "string" }
output_schema = { answer = "string" }
output_intermediate = true

# ----------------------------
# [deployment.<name>]
# Hosting configuration
# ----------------------------
[deployment.default]
runtime = "fastapi"
expose = ["task.analysis"]
port = 8080

# ----------------------------
# [vars]
# Secrets and environment substitutions
# ----------------------------
[vars]
